-- SELECT * FROM customer limit 20; (checking data)

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchased_amount) 
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchased_amount
from customer
where discount_applied = 'Yes' and purchased_amount > (select AVG(purchased_amount) from customer)


-- Q3. Which are the top 5 products wi th the highest average review rating?
select item_purchased, 
ROUND(AVG(review_rating :: numeric), 2) as "Average product rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
ROUND(AVG(purchased_amount), 2)
from customer
where shipping_type IN ('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
select subscription_status,
COUNT(customer_id) as "Total customers",
ROUND(AVG(purchased_amount), 2) as avg_spend,
SUM(purchased_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue DESC, avg_spend DESC


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate 
from customer
group by item_purchased
order by discount_rate desc
limit 5


--Q7. Segment customers into New, Returning, and Loyal based on their total number of 
-- previous purchases, and show the count of each segment. 
with customer_type_table as(
select previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, 
COUNT(*) AS total_customers
from customer_type_table
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 
with item_counts as(
select category, 
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY SUM(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, 
COUNT(customer_id) as total_repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status 


--Q10. What is the revenue contribution of each age group? 
select age_group,
COUNT(customer_id) AS total_customers,
SUM(purchased_amount) AS total_revenue
from customer
group by age_group
